# Project-wide Gradle settings.
# IDE (VS Code / Android Studio) and CLI will use Java 17 for AGP 8.7.2.
org.gradle.java.home=/opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home

org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# AndroidX & Jetpack Compose
android.useAndroidX=true
android.nonTransitiveRClass=true
